#!/usr/bin/env python3
"""
clens.py — Claude Session Token Capacity Monitor
================================================
A lightweight, zero-dependency terminal dashboard that parses the local
.jsonl session log tracks generated by Anthropic's Claude agentic tools.

Targets:  ~/.claude/projects/**/*.jsonl  (Windows/Linux/macOS)
Outputs:  ANSI-styled ASCII dashboard with token gauge & capacity index.
"""

import os
import json
import sys
import glob
import shutil

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SEPARATOR    = "\u2501"   # ━  (BOX DRAWINGS HEAVY HORIZONTAL)
BLOCK_FILL   = "\u2588"   # █  (FULL BLOCK)
BLOCK_SHADE  = "\u2591"   # ░  (LIGHT SHADE)
GAUGE_WIDTH  = 30
CAPACITY_MAX = 3_000_000

# ---- ANSI escape sequences -----------------------------------------------
GREEN   = "\033[92m"
YELLOW  = "\033[93m"
RED     = "\033[91m"
RESET   = "\033[0m"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def fmt(n: int) -> str:
    """Format an integer with comma-separated thousands."""
    return f"{n:,}"


def ansi(s: str) -> None:
    """Write a string to stdout."""
    sys.stdout.write(s + "\n")


# ---------------------------------------------------------------------------
# Filesystem discovery
# ---------------------------------------------------------------------------

def find_claude_log_dir() -> str:
    """Return the cross-platform path to the Claude projects log directory."""
    home = os.path.expanduser("~")
    return os.path.join(home, ".claude", "projects")


def find_latest_jsonl(log_dir: str) -> str | None:
    """
    Recursively walk *log_dir*, collecting every ``*.jsonl`` file,
    then return the one with the highest ``os.path.getmtime`` (most
    recently written).
    Returns *None* when no JSONL tracks are found.
    """
    candidates: list[str] = []

    if not os.path.isdir(log_dir):
        return None

    try:
        pattern = os.path.join(log_dir, "**", "*.jsonl")
        candidates = glob.glob(pattern, recursive=True)
    except Exception:
        for root, _dirs, files in os.walk(log_dir):
            for f in files:
                if f.endswith(".jsonl"):
                    candidates.append(os.path.join(root, f))

    if not candidates:
        return None

    candidates.sort(key=os.path.getmtime, reverse=True)
    return candidates[0]


# ---------------------------------------------------------------------------
# JSONL streaming parser
# ---------------------------------------------------------------------------

def parse_jsonl(filepath: str):
    """
    Line-by-line secure JSONL parser.

    Yields parsed Python dicts.  Silently skips blank lines and lines
    that raise ``json.JSONDecodeError``.
    """
    with open(filepath, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


# ---------------------------------------------------------------------------
# Token accumulation
# ---------------------------------------------------------------------------

def accumulate_tokens(filepath: str):
    """
    Stream the JSONL file and return a 3-tuple:

        (input_tokens, output_tokens, cache_read_input_tokens)

    Values are pulled from the nested key path:

        message -> usage -> <token_key>
    """
    inp = 0
    out = 0
    cache = 0

    for obj in parse_jsonl(filepath):
        usage = None
        message = obj.get("message") if "message" in obj else None
        if message is None and "data" in obj:
            message = obj["data"].get("message")

        if isinstance(message, dict):
            usage = message.get("usage")
        elif isinstance(obj.get("usage"), dict):
            usage = obj["usage"]

        if isinstance(usage, dict):
            inp   += usage.get("input_tokens", 0)
            out   += usage.get("output_tokens", 0)
            cache += usage.get("cache_read_input_tokens", 0)

    return inp, out, cache


# ---------------------------------------------------------------------------
# Gauge rendering
# ---------------------------------------------------------------------------

def render_gauge(pct: float) -> str:
    """
    Render a 30-character ASCII capacity gauge.

    ``pct`` is a float in 0–100 (or slightly above).
    """
    filled = max(0, min(GAUGE_WIDTH, int(GAUGE_WIDTH * pct / 100.0)))
    empty  = GAUGE_WIDTH - filled
    return BLOCK_FILL * filled + BLOCK_SHADE * empty


def colour_for_pct(pct: float) -> tuple[str, str]:
    """
    Return (colour_code, status_label) based on capacity percentage.

    Thresholds:
        <  80 %  → green  [● MONITORING]
        80-94 %  → yellow [● CHECKPOINTING]
        >= 95 %  → red    [● CRITICAL LIMIT]
    """
    if pct >= 95.0:
        return RED, "[● CRITICAL LIMIT]"
    if pct >= 80.0:
        return YELLOW, "[● CHECKPOINTING]"
    return GREEN, "[● MONITORING]"


# ---------------------------------------------------------------------------
# Dashboard render
# ---------------------------------------------------------------------------

def render_dashboard(
    log_dir: str,
    filepath: str,
    inp: int,
    out: int,
    cache: int,
) -> None:
    """Compose and print the full terminal dashboard."""
    total = inp + out + cache
    pct   = (total / CAPACITY_MAX) * 100.0
    colour, status = colour_for_pct(pct)
    gauge = render_gauge(pct)

    term_w = shutil.get_terminal_size().columns - 4
    short_path = filepath
    if len(short_path) > term_w:
        short_path = "…" + short_path[-(term_w - 1):]

    lines: list[str] = []

    lines.append("")
    lines.append(f"  {GREEN}CLENS  —  Claude Session Token Monitor{RESET}")
    lines.append(f"  {SEPARATOR * (term_w)}")

    lines.append(f"  Project Root : {log_dir}")
    lines.append(f"  Active Track : {short_path}")
    lines.append(f"  {SEPARATOR * (term_w)}")

    lines.append(f"  {colour}{status}{RESET}")
    lines.append(f"  {gauge}  {colour}{pct:.1f}%{RESET}")
    lines.append(f"  {SEPARATOR * (term_w)}")

    lines.append(f"  Total Tokens : {fmt(total)}  /  {fmt(CAPACITY_MAX)}  threshold")
    lines.append("")

    lines.append(f"  Input  : {fmt(inp)}")
    lines.append(f"  Output : {fmt(out)}")
    lines.append(f"  Cache  : {fmt(cache)}  (cache_read_input_tokens)")
    lines.append("")
    lines.append(f"  {SEPARATOR * (term_w)}")
    lines.append(f"  Session capacity benchmark : {fmt(CAPACITY_MAX)} tokens")
    lines.append("")

    sys.stdout.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Main CLI entry point."""
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    log_dir = find_claude_log_dir()

    if not os.path.isdir(log_dir):
        ansi(f"{RED}Error:{RESET} Claude projects directory not found.")
        ansi(f"  Expected: {log_dir}")
        ansi(f"  Make sure the Claude CLI or VS Code extension has been run at least once.")
        sys.exit(1)

    latest = find_latest_jsonl(log_dir)
    if latest is None:
        ansi(f"{YELLOW}Notice:{RESET} No .jsonl session tracks found under:")
        ansi(f"  {log_dir}")
        ansi(f"  Run a Claude agentic session first to generate log data.")
        sys.exit(0)

    inp, out, cache = accumulate_tokens(latest)

    render_dashboard(log_dir, latest, inp, out, cache)


if __name__ == "__main__":
    main()